// <auto-generated />
namespace OnlineHelpDesk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Contact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contact));
        
        string IMigrationMetadata.Id
        {
            get { return "202007141809041_Contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
